name: account_easy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.65.0
  uuid: ^4.2.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
